### PR TITLE
fix: modify the depth setting in Fory to prevent duplicate registrations.

### LINKED ISSUE #2840: register class after serialization using ThreadSafeFory  caused classInfo.classDef NPE
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fory/issues) and found no similar issues.

### Version

version：0.12.3
os：windows 11

### Component(s)

Java

### Minimal reproduce step

错误写法：
private static final ThreadSafeFory fory = new ThreadLocalFory(classLoader -> {
    Fory f = Fory.builder().withLanguage(Language.JAVA)
      .withClassLoader(classLoader).build();
    return f;
  });
fory.register(SomeClass.class);
Struct2 struct2 = (Struct2) fory.deserializeJavaObject(bytes, Struct2.class);

### What did you expect to see?

正确反序列化

### What did you see instead?

org.apache.fory.exception.DeserializationException: Failed to deserialize input
	at org.apache.fory.util.ExceptionUtils.handleReadFailed(ExceptionUtils.java:66)
	at org.apache.fory.Fory.deserializeJavaObject(Fory.java:1226)
	at org.apache.fory.Fory.deserializeJavaObject(Fory.java:1197)
	at org.apache.fory.ThreadLocalFory.deserializeJavaObject(ThreadLocalFory.java:207)
	at cc.metafusion.bossai.service.common.util.ForyUtils.deserialize(ForyUtils.java:46)
	at cc.metafusion.bossai.service.common.model.mq.SourceEventData.of(SourceEventData.java:43)
	at cc.metafusion.data.event.bridge.core.queue.MsgProducer.translate(MsgProducer.java:23)
	at com.lmax.disruptor.RingBuffer.translateAndPublish(RingBuffer.java:967)
	at com.lmax.disruptor.RingBuffer.publishEvent(RingBuffer.java:487)
	at cc.metafusion.data.event.bridge.core.queue.MsgProducer.lambda$onData$0(MsgProducer.java:40)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at cc.metafusion.data.event.bridge.core.queue.MsgProducer.onData(MsgProducer.java:39)
	at cc.metafusion.data.event.bridge.core.startup.RocketMqStartup.lambda$init$0(RocketMqStartup.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.fory.meta.ClassDef.replaceRootClassTo(org.apache.fory.resolver.ClassResolver, java.lang.Class)" because "classInfo.classDef" is null
	at org.apache.fory.resolver.ClassResolver.readClassInfoWithMetaShare(ClassResolver.java:1628)
	at org.apache.fory.Fory.deserializeJavaObject(Fory.java:1216)
	... 12 common frames omitted

Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.fory.meta.ClassDef.replaceRootClassTo(org.apache.fory.resolver.ClassResolver, java.lang.Class)" because "classInfo.classDef" is null

### Anything Else?

正确写法
private static final ThreadSafeFory fory = new ThreadLocalFory(classLoader -> {
    Fory f = Fory.builder().withLanguage(Language.JAVA)
      .withClassLoader(classLoader).build();
    // 需要注册的类在这里全部注册完
    f.register(SomeClass.class);
    return f;
  });
Struct2 struct2 = (Struct2) fory.deserializeJavaObject(bytes, Struct2.class);

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by mengnankkkk**
## Why?
By adding a depth field to the fory instance to indicate whether it is registered, and then checking in the TypeResolver, it is ensured that the fory instance cannot be registered after serialization, otherwise a foryexception will be thrown.

## Related issues
Close #2840 

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

### CODE REVIEW

File: java/fory-core/src/main/java/org/apache/fory/ThreadLocalFory.java [hunk 1]
```diff
@@ -78,10 +81,12 @@ public ThreadLocalFory(Function<ClassLoader, Fory> foryFactory) {
   @Internal
   @Override
   public void registerCallback(Consumer<Fory> callback) {
-    factoryCallback = factoryCallback.andThen(callback);
-    for (LoaderBinding binding : allFory.keySet()) {
-      binding.visitAllFory(callback);
-      binding.setBindingCallback(factoryCallback);
+    synchronized (callbackLock) {
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/ThreadLocalFory.java:82]: could we also add lock to `ThreadPoolFory`? Or would it be possible to add lock in `AbstactThreadSafeFory`?

File: java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java [hunk 2]
```diff
@@ -373,4 +373,137 @@ public void testSerializerRegister() {
...
+    ExecutorService executor = Executors.newFixedThreadPool(4);
+    ConcurrentHashMap<String, Throwable> errors = new ConcurrentHashMap<>();
+
+    try {
+      ThreadSafeFory fory = Fory.builder().requireClassRegistration(true).buildThreadLocalFory();
+
+      fory.register(BeanA.class);
+      fory.register(BeanB.class);
+      BeanA beanA = BeanA.createBeanA(2);
+      byte[] bytesA = fory.serialize(beanA);
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java]: You only register once, then serialize with that Fory instance multiple times. This should work as before. I don't think this PR fix anything.

IMO, the real issue is that the `serialize` has been executed a few times, but after that, users call `register` method. Such pattern are not allowed, no register should be invoked after any serialize/deserialize has been executed.

As for register  itself, may just add `synchronized` to method is enough

Comment (mengnankkkk) [reply java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java]: Okay, I understand the problem and will make changes. Thank you for your code review.

**Comment by chaokunyang** [comment]
@mengnankkkk  How about reuse `depth` field in `Fory` instance, you can set it to -1 by default, and when register any Serializer/Class, check whether `depth` is still -1. If it `>=` 0, it means serialize/deserialize has happened, then you can just thow exception. You can add this check in `TypeResolver`

**Comment by mengnankkkk** [comment]
> @mengnankkkk How about reuse `depth` field in `Fory` instance, you can set it to -1 by default, and when register any Serializer/Class, check whether `depth` is still -1. If it `>=` 0, it means serialize/deserialize has happened, then you can just thow exception. You can add this check in `TypeResolver`

OK, I'll do my best. I hope it won't be like the last PR attempt, where it couldn't be resolved. If it really can't be resolved, I'll have to ask you for advice again.[doge]

**Comment by mengnankkkk** [comment]
@chaokunyang Hello, I've implemented the basic checking phase as you requested, but I'm encountering a problem:

`ThreadPoolFory` manages multiple `Fory` serialization instances. When one thread starts serializing/deserializing an instance, another thread calls registerCallback to register a new class.

`registerCallback` attempts to apply the new class to all Fory instances in the pool, including the one currently being used by thread A or already used. Since the instance's internal state (such as the class ID mapping table) might have been "frozen" (Finalized) during the first serialization, attempting to register a new class at this point would corrupt its state, causing failure.

Using a synchronization lock would result in poor performance. Adding a volatile boolean global variable and checking this flag in the `registerCallback` method would immediately throw an `IllegalStateException` if the flag is true (meaning the "execution phase" has begun), preventing the registration. However, this causes many tests to fail, which seems inconsistent with multithreading requirements.

How should I handle this problem?! Help!

**Comment by chaokunyang** [comment]
I don't think this issue exists. If one of fory instance has executed the serialization, the depth will not be -1. And the registerCallback should fail on that instance And propagate the exception to the callsite

**Comment by chaokunyang** [comment]
You should not add any new global variable. We have no plans to introduce any new global flags in fory.

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 3]
```diff
@@ -1606,6 +1602,10 @@ private void throwDepthDeserializationException() {
             method));
   }
 
+  public boolean hasSerializedOrDeserialized() {
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]: Remove this method

**Comment by chaokunyang** [comment]
Could we add a simple test to verify that register after serialize will throw exception?

File: java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java [hunk 4]
```diff
@@ -111,6 +111,14 @@ protected TypeResolver(Fory fory) {
     metaStringResolver = fory.getMetaStringResolver();
   }
 
+  protected final void checkRegisterAllowed() {
+    if (fory.getDepth() >= 0) {
+      throw new IllegalStateException(
+          "Cannot register class/serializer after serialization/deserialization has started. "
+              + "Please register all classes before using Fory.");
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java]:
```suggestion
              + "Please register all classes before invoking `serialize/deserialize` methods of Fory.");
```

File: java/fory-core/src/main/java/org/apache/fory/ThreadLocalFory.java [hunk 5]
```diff
@@ -59,7 +60,9 @@ public ThreadLocalFory(Function<ClassLoader, Fory> foryFactory) {
         ThreadLocal.withInitial(
             () -> {
               LoaderBinding binding = new LoaderBinding(foryFactory);
-              binding.setBindingCallback(factoryCallback);
+              synchronized (callbackLock) {
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/ThreadLocalFory.java]: why we need this, this seems fix nothing

File: java/fory-core/src/main/java/org/apache/fory/pool/ClassLoaderForyPooled.java [hunk 6]
```diff
@@ -98,6 +98,7 @@ public Fory getFory() {
 
   public void returnFory(Fory fory) {
     Objects.requireNonNull(fory);
+    fory.reset();
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/pool/ClassLoaderForyPooled.java]: remove it, it introduce extra reset

File: java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java [hunk 7]
```diff
@@ -111,6 +111,14 @@ protected TypeResolver(Fory fory) {
     metaStringResolver = fory.getMetaStringResolver();
   }
 
+  protected final void checkRegisterAllowed() {
+    if (fory.getDepth() >= 0) {
+      throw new IllegalStateException(
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/resolver/TypeResolver.java]:
```suggestion
      throw new ForyExcetion(
```

File: java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java [hunk 8]
```diff
@@ -373,4 +373,40 @@ public void testSerializerRegister() {
...
+    Assert.assertEquals(fory.getDepth(), -1);
+    BeanA beanA = BeanA.createBeanA(2);
+    byte[] bytes = fory.serialize(beanA);
+    Assert.assertEquals(fory.getDepth(), -1);
+    fory.deserialize(bytes);
+    Assert.assertEquals(fory.getDepth(), -1);
+  }
+
+  @Test
+  public void testRegisterAfterSerializeThrowsException() {
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java]: I don't see any code  in this test `assertThrows` the exception has been raised. Please update this test.

And please be consise, most of codes in this tests doesn't test the unexpected register behaviour. Please remove such code, and concentrated on unexpected register behaviour test only.

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 9]
```diff
@@ -1662,6 +1667,14 @@ public void setDepth(int depth) {
     this.depth = depth;
   }
 
+  public void beforeSerialize() {
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]: remove such methods, please keep the implmentation simple

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 10]
```diff
@@ -1572,7 +1573,7 @@ public void resetWrite() {
     metaStringResolver.resetWrite();
     serializationContext.resetWrite();
     bufferCallback = null;
-    depth = 0;
+    depth = -1;
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]:
```suggestion
    depth = 0;
```
I think this should be 0, otherwise the register can still be invoked

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 11]
```diff
@@ -1581,8 +1582,8 @@ public void resetRead() {
     metaStringResolver.resetRead();
     serializationContext.resetRead();
     peerOutOfBandEnabled = false;
-    depth = 0;
     classDefEndOffset = -1;
+    depth = -1;
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]: ditto

File: java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java [hunk 12]
```diff
@@ -373,4 +374,63 @@ public void testSerializerRegister() {
...
+    Assert.assertEquals(fory.getDepth(), -1);
+    BeanA beanA = BeanA.createBeanA(2);
+    byte[] bytes = fory.serialize(beanA);
+    Assert.assertEquals(fory.getDepth(), -1);
+    fory.deserialize(bytes);
+    Assert.assertEquals(fory.getDepth(), -1);
+  }
+
+  @Test
+  public void testRegisterAfterSerializeThrowsException() throws Exception {
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java:379]: Seems this test doesn't capture the bug in set `depth` to `-1`, please update this test to make it actually capture such bugs

File: java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java [hunk 13]
```diff
@@ -373,4 +374,63 @@ public void testSerializerRegister() {
...
         });
   }
+
+  @Test
+  public void testGetDepth() {
+    Fory fory = Fory.builder().requireClassRegistration(false).build();
+    Assert.assertEquals(fory.getDepth(), -1);
+    BeanA beanA = BeanA.createBeanA(2);
+    byte[] bytes = fory.serialize(beanA);
+    Assert.assertEquals(fory.getDepth(), -1);
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java]:
```suggestion
    Assert.assertEquals(fory.getDepth(), 0);
```

File: java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java [hunk 14]
```diff
@@ -373,4 +374,63 @@ public void testSerializerRegister() {
...
+            () -> {
+              fory.serialize(new Foo());
+            });
+    t.start();
+
+    Assert.assertTrue(writeStarted.await(5, TimeUnit.SECONDS));
+
+    Assert.assertThrows(ForyException.class, () -> fory.register(BeanA.class));
+
+    allowFinish.countDown();
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java]: why we need such code? What does it test exactly?
Please keep things simple. You can just use Fory and TheadSafeFory(ThreadLocalFory/ThradPoolFory) to serialize an object, then invoke register, adn assert it raise exception. I think this will be enough

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 15]
```diff
@@ -803,11 +803,16 @@ public <T> T deserialize(byte[] bytes, Class<T> type) {
       assert !peerOutOfBandEnabled : "Out of band buffers not passed in when deserializing";
       return deserializeJavaObject(buffer, type);
     }
+    int prevDepth = this.depth;
+    if (crossLanguage) {
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]: why we need this?

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 16]
```diff
@@ -803,11 +803,16 @@ public <T> T deserialize(byte[] bytes, Class<T> type) {
       assert !peerOutOfBandEnabled : "Out of band buffers not passed in when deserializing";
       return deserializeJavaObject(buffer, type);
     }
+    int prevDepth = this.depth;
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]: TBO, this is also a little strange

File: java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java [hunk 17]
```diff
@@ -378,59 +378,36 @@ public void testSerializerRegister() {
...
 
-    allowFinish.countDown();
-    t.join();
+  @Test
+  public void testRegisterAfterSerializeThrowsExceptionWithForyPool() {
+    ThreadSafeFory fory =
+        Fory.builder().requireClassRegistration(true).buildThreadSafeForyPool(1, 2);
+    fory.register(BeanA.class);
+    fory.serialize("ok");
+    Assert.assertThrows(ForyException.class, () -> fory.register(BeanA.class));
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/ThreadSafeForyTest.java]: You should register another class instead of same class.

File: java/fory-core/src/main/java/org/apache/fory/Fory.java [hunk 18]
```diff
@@ -176,6 +177,9 @@ public Fory(ForyBuilder builder, ClassLoader classLoader) {
 
   @Override
   public void register(Class<?> cls) {
+    if (depth >= 0) {
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/Fory.java]: Seems this is not needed, we've checked it in `TypeResolver#register`

File: java/fory-core/src/test/java/org/apache/fory/serializer/ArraySerializersTest.java [hunk 19]
```diff
@@ -43,39 +43,90 @@
 
 public class ArraySerializersTest extends ForyTestBase {
 
+  private static void prewarm(Fory... forys) {
```
Comment (chaokunyang) [inline java/fory-core/src/test/java/org/apache/fory/serializer/ArraySerializersTest.java]: could we rename to `registerTypes`?

**Comment by mengnankkkk** [comment]
> LGTM overall, after addressed little minor issues, we can merge it. Thanks for your contribution!

Thank you for your code review. I really learned a lot in the process of fixing this PR. Thank you for reviewing the code and the solution design. It was really helpful. I will fix the simple issues right away. Thank you again!
