### PR TITLE
fix(java): retain serializers in graalvm native images

### LINKED ISSUE #2669: [Java][Native Image] `ensureSerializersCompiled` will remove custom serializers
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fory/issues) and found no similar issues.

### Version

OS: ArchLinux (6.16.7-zen1-1-zen)
Fory: 'org.apache.fory:fory-core:0.13.0-SNAPSHOT'
Failing JDK: GraalVM 23.0.2+7.1 (build 23.0.2+7-jvmci-b01)

### Component(s)

Java

### Minimal reproduce step

Clone [the reproducer project](https://github.com/gudzpoz/fory-native-image-reproducer/tree/ensure-custom)

Reproducing steps:

```console
$ git checkout subclass-fields
$ ./gradlew run # pass
$ ./gradlew nativeCompile
$ app/build/native/nativeCompile/test # fail
Exception in thread "main" org.apache.fory.exception.SerializationException: java.lang.RuntimeException: Class class org.example.App$Custom is not registered
        at org.apache.fory.Fory.processSerializationError(Fory.java:371)
        at org.apache.fory.Fory.serialize(Fory.java:340)
        at org.apache.fory.Fory.serialize(Fory.java:288)
        at org.example.App.main(App.java:24)
        at java.base@23.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.lang.RuntimeException: Class class org.example.App$Custom is not registered
        at org.apache.fory.resolver.TypeResolver.getSerializerClassFromGraalvmRegistry(TypeResolver.java:600)
        at org.apache.fory.resolver.ClassResolver.getSerializerClass(ClassResolver.java:854)
        at org.apache.fory.resolver.ClassResolver.getSerializerClass(ClassResolver.java:846)
        at org.apache.fory.resolver.ClassResolver.createSerializer(ClassResolver.java:1252)
        at org.apache.fory.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1174)
        at org.apache.fory.resolver.ClassResolver.getRawSerializer(ClassResolver.java:839)
        at org.example.AppForyRefCodec_0.<init>(AppForyRefCodec_0.java:54)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:241)
        at java.base@23.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:102)
        at java.base@23.0.2/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.base@23.0.2/java.lang.invoke.Invokers$Holder.invoke_MT(Invokers$Holder)
        at org.apache.fory.serializer.Serializers.newSerializer(Serializers.java:101)
        at org.apache.fory.resolver.ClassResolver.createSerializer(ClassResolver.java:1253)
        at org.apache.fory.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1174)
        at org.apache.fory.Fory.write(Fory.java:412)
        at org.apache.fory.Fory.serialize(Fory.java:334)
        ... 3 more
```

GitHub workflow reproducer: https://github.com/gudzpoz/fory-native-image-reproducer/actions/runs/18038616597/job/51331417582

### What did you expect to see?

The test should pass.

### What did you see instead?

`java.lang.RuntimeException: Class class org.example.App$Custom is not registered` when the serializer has been registered.

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by gudzpoz**
## Why?

Custom serializers are not retained during GraalVM native image builds.

## What does this PR do?

The original code checks against `initialClassInfos` and removes serializers outside the set during native image builds. This PR removes that as well as `initialClassInfos`.

I don't know what `initialClassInfos` is for, because it is only involved in clearing serializers, which this PR is to remove.

Also, since the tests before weren't retaining some serializers, it turns out the original `native-image.properties` might be incomplete. And I added more classes to `--initialize-at-build-time` as is hinted by the `native-image` command.

## Related issues

- Fixes #2669

### CODE REVIEW

**Comment by chaokunyang** [comment]
The `initialClassInfos` was used to record fory registered serializer for JDK types to avoid serializers for thoese types are cleared. But since we use GraalvmSerializerHolder to aviod instance of generated serializer, there won't be serializer instance at build time. So we can remove the clear logic.

Nice catch, thanks for this fix.

File: java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java [hunk 1]
```diff
@@ -1802,15 +1794,6 @@ public void ensureSerializersCompiled() {
               }
             }
           });
-      if (GraalvmSupport.isGraalBuildtime()) {
-        classInfoMap.forEach(
-            (cls, classInfo) -> {
-              if (classInfo.serializer != null
-                  && !extRegistry.initialClassInfos.contains(classInfo)) {
-                classInfo.serializer = null;
```
Comment (chaokunyang) [inline java/fory-core/src/main/java/org/apache/fory/resolver/ClassResolver.java:1810]: Actually we do need the clear, otherwise current Fory instance may hold some unexpected serializer. For example, `ObjectStreamSerializer` hold CompatibleSerializer serializer instead of generated by Fory.

```java
      if (GraalvmSupport.isGraalBuildtime()) {
        // trigger serializer constructor method handle generate.
        Serializers.newSerializer(fory, type, sc);
      }
      if (sc == CompatibleSerializer.class || GraalvmSupport.isGraalBuildtime()) {
        // skip init generated serializer at graalvm build time
        this.slotsSerializer = new CompatibleSerializer(fory, type, fieldResolver);
      } else {
        this.slotsSerializer = (CompatibleSerializerBase) Serializers.newSerializer(fory, type, sc);
      }
```
