### PR TITLE
fix(go): add configurable fieldCount and fieldDepth guardrails

### LINKED ISSUE #3619: [Go] unbounded allocation and recursion in go typedef deserialization
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fory/issues) and found no similar issues.

### Version

v0.17.0

### Component(s)

Go

### Minimal reproduce step

```go
func TestTypeDefFieldCountOOMPanic(t *testing.T) {
	fory := NewFory()
	header := int64(HAS_FIELDS_META_FLAG | 8)

	// metaHeaderByte value of 31 triggers the extended VarUint32 field-count path.
	buffer := NewByteBuffer(make([]byte, 0, 8))
	buffer.WriteByte(31)
	buffer.WriteVarUint32(2000000000)
	buffer.WriteUint8(0)
	buffer.WriteVarUint32(0)
	buffer.SetReaderIndex(0)

	_, err := decodeTypeDef(fory, buffer, header)
	if err == nil {
		t.Fatal("expected error for oversized fieldCount, got nil")
	}
}

func TestTypeDefNestedRecursionStackOverflowPanic(t *testing.T) {
	depth := 20000000
	buffer := NewByteBuffer(make([]byte, 0, depth*2))
	for i := 0; i < depth; i++ {
		buffer.WriteVarUint32Small7(uint32(LIST) << 2)
	}
	buffer.WriteVarUint32Small7(uint32(INT32) << 2)
	buffer.SetReaderIndex(0)

	bufErr := &Error{}
	_, err := readFieldTypeWithFlags(buffer, 0, bufErr)
	if err == nil {
		t.Fatal("expected error for excessive nesting depth, got nil")
	}
}
```

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by ayush00git**
## Why?
Malicious payloads could specify a massive `fieldCount`, causing the runtime to attempt an unbounded memory allocation.
Deeply nested schema definitions (like a LIST of LIST...) could trigger unbounded recursion, exceeding the goroutine stack limit and crashing the process.

## What does this PR do?
Added a hard limit of 10,000 fields and a buffer-remaining check in decodeTypeDef to prevent massive slice allocations.
Added a depth parameter to `readFieldType` and `readFieldTypeWithFlags`, capping nested schema definitions at a maximum depth of 64.

## Related issues
Closes #3619 

## AI Contribution Checklist

- [ ] Substantial AI assistance was used in this PR: `yes` / `no`
- [ ] If `yes`, I included a completed [AI Contribution Checklist](https://github.com/apache/fory/blob/main/AI_POLICY.md#9-contributor-checklist-for-ai-assisted-prs) in this PR description and the required `AI Usage Disclosure`.
- [ ] If `yes`, my PR description includes the required `ai_review` summary and screenshot evidence of the final clean AI review results from both fresh reviewers on the current PR diff or current HEAD after the latest code changes.

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

### CODE REVIEW

**Comment by ayush00git** [comment]
@chaokunyang i'm planning to create these bounds configurable, moving them to the `Config`.

**Comment by ayush00git** [comment]
@chaokunyang have a look

File: go/fory/fory.go [hunk 1]
```diff
@@ -66,6 +68,8 @@ func defaultConfig() Config {
 		IsXlang:           false,
 		MaxCollectionSize: 1_000_000,
 		MaxBinarySize:     64 * 1024 * 1024,
+		MaxTypeDefFields:  10000,
+		MaxTypeDefDepth:   64,
```
Comment (chaokunyang) [inline go/fory/fory.go]: You can reuse MaxDepth, we'd better to kepp config options minimal

File: go/fory/fory.go [hunk 2]
```diff
@@ -66,6 +68,8 @@ func defaultConfig() Config {
 		IsXlang:           false,
 		MaxCollectionSize: 1_000_000,
 		MaxBinarySize:     64 * 1024 * 1024,
+		MaxTypeDefFields:  10000,
```
Comment (chaokunyang) [inline go/fory/fory.go]:
```suggestion
		MaxTypeFields:  10000,
```

**Review by chaokunyang — APPROVED** [review]
LGTM
