### PR TITLE
fix(go): ensure physical buffer space for unsafe varint fast-paths

### LINKED ISSUE #3612: [Go] `unsafe` Varint fast-path writes/reads more bytes than reserved in struct serializer
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fory/issues) and found no similar issues.

### Version

0.17.0

### Component(s)

Go

### Minimal reproduce step

The following self-contained Go test demonstrates the write-path issue using a sentinel-value check. It can be added to go/fory/buffer_test.go:

```go
func TestUnsafePutVarUint32OOBWrite(t *testing.T) {
    // Construct a ByteBuffer backed by a slice where len == writerIndex + 5.
    // This replicates the condition where Reserve(5) is satisfied without expanding
    // the buffer, but UnsafePutVarUint32 then writes 8 physical bytes.

    const sentinelByte = byte(0xAB)
    const totalCap = 16 // backing large enough to observe the overwrite safely
    backing := make([]byte, totalCap, totalCap)

    // Fill bytes [5, totalCap) with sentinel values.
    for i := 5; i < totalCap; i++ {
        backing[i] = sentinelByte
    }

    // Simulate struct.go's fast-path: Reserve(MaxVarintSize=5) on a tight buffer.
    // Expose only 5 bytes of len so Reserve(5) returns immediately.
    buf := NewByteBuffer(backing[:5]) // len=5, cap=16

    // Replicate exactly what struct.go:342 does for a uint32 varint field:
    buf.Reserve(5) // needed(5) <= len(5) → returns immediately, NO growth

    // A uint32 value >= 2^28 encodes to 5 varint bytes → triggers 8-byte bulk write.
    written := buf.UnsafePutVarUint32(0, 1<<28)
    if written != 5 {
        t.Fatalf("expected 5 bytes written, got %d", written)
    }

    // Bytes at indices 5, 6, 7 are past Reserve(5)'s guaranteed region.
    // If they differ from the sentinel, the 8-byte write overflowed the reserved region.
    overwritten := 0
    for i := 5; i < 8; i++ {
        if backing[i] != sentinelByte {
            t.Logf("backing[%d] = 0x%02X (overwritten, was 0x%02X)", i, backing[i], sentinelByte)
            overwritten++
        }
    }
    if overwritten > 0 {
        t.Errorf("UnsafePutVarUint32 wrote %d byte(s) past Reserve(5)'s guaranteed region "+
            "(contract requires Reserve(8) per buffer.go:661)", overwritten)
    }
}

```

### What did you expect to see?

- Expected: test passes — no bytes written past index 4.

### What did you see instead?

- Actual: backing[5], backing[6], backing[7] are overwritten — 3 bytes past the reserved region.

Note on the test design: `cap=16` is used intentionally so the overflow lands within the backing array and the test runs safely without corrupting other heap objects. In production, when a `ByteBuffer` is created from an inbound network slice via `NewByteBuffer(inboundSlice)` (where `len == cap`), those 3 bytes escape the Go allocation and corrupt adjacent heap memory.

### Anything Else?

The Go runtime's struct serialization fast-path in `struct.go` violates the documented contract of `UnsafePutVarUint32` and `UnsafeReadVarUint32` in `buffer.go`. Specifically:

- `UnsafePutVarUint32` documents that the caller must call `Reserve(8)` (because it performs an 8-byte bulk write for 5-byte varints), but `struct.go` only calls `Reserve(MaxVarintSize)`, which is `5` for `uint32/int32` varint fields.
- `UnsafeReadVarUint32` physically reads 8 bytes, but the fast-path guard in `struct.go` only checks `remaining() >= MaxVarintSize` (which can be 5).
This is a correctness bug / contract violation — the mismatch can cause writes past the end of a buffer's allocated memory in any situation where the buffer's capacity is not generously over-sized (e.g. when a `ByteBuffer` is constructed from a pre-existing `[]byte` via `NewByteBuffer`).

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by ayush00git**
## Why?

The Go runtime's struct serialization fast-path in `struct.go` violates the documented contract of `UnsafePutVarUint32` and `UnsafeReadVarUint32` in `buffer.go`.
- `UnsafePutVarUint32` documents that the caller must call `Reserve(8)` (because it performs an 8-byte bulk write for 5-byte varints), but `struct.go` only calls `Reserve(MaxVarintSize)`, which is 5 for uint32/int32 varint fields.
- `UnsafeReadVarUint32` physically reads 8 bytes, but the fast-path guard in `struct.go` only checks `remaining() >= MaxVarintSize` (which can be 5).
## What does this PR do?

- Add +8 byte padding to struct varint reservation and remaining-check guardrails in struct.go. This ensures that the underlying unsafe bulk memory operations (8-byte loads/stores) always stay within the allocated backing array, even when the logical varint size is smaller (e.g., 5 bytes).

- Includes a regression test in buffer_test.go verifying the physical write width of `UnsafePutVarUint32`.
## Related issues

Closes #3612 

## AI Contribution Checklist

- [ ] Substantial AI assistance was used in this PR: `yes` / `no`
- [ ] If `yes`, I included a completed [AI Contribution Checklist](https://github.com/apache/fory/blob/main/AI_POLICY.md#9-contributor-checklist-for-ai-assisted-prs) in this PR description and the required `AI Usage Disclosure`.
- [ ] If `yes`, my PR description includes the required `ai_review` summary and screenshot evidence of the final clean AI review results from both fresh reviewers on the current PR diff or current HEAD after the latest code changes.

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

### CODE REVIEW

**Comment by ayush00git** [comment]
@chaokunyang have a look.

File: go/fory/buffer_test.go [hunk 1]
```diff
@@ -81,3 +81,33 @@ func checkVarintWrite(t *testing.T, buf *ByteBuffer, value int32) {
 	require.Equal(t, buf.ReaderIndex(), buf.WriterIndex())
 	require.Equal(t, value, varInt)
 }
+
+// TestUnsafePutVarUint32PhysicalWriteWidth verifies that UnsafePutVarUint32 performs
+// an 8-byte physical write for 5-byte varints and that Reserve(8) (as required by
+// buffer.go:661) keeps those 8 bytes within the backing array.
+func TestUnsafePutVarUint32PhysicalWriteWidth(t *testing.T) {
```
Comment (chaokunyang) [inline go/fory/buffer_test.go:88]: Please add another test to cover struct.go change

**Comment by ayush00git** [comment]
@chaokunyang please have a look.

**Review by chaokunyang — APPROVED** [review]
LGTM
