### PR TITLE
fix(java): Deserialize nested HashMap subclasses

### LINKED ISSUE #3337: [Java] Fails deserializing nested HashMap subclasses with inherited generic type parameters
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fory/issues) and found no similar issues.

### Version

0.15.0

### Component(s)

Java

### Minimal reproduce step

Here are some tests reproducing the issue by failing:

```java
package org.apache.fory.serializer.collection;

import static org.testng.Assert.assertEquals;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeSet;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.apache.fory.Fory;
import org.apache.fory.ForyTestBase;
import org.apache.fory.config.CompatibleMode;
import org.apache.fory.config.Language;
import org.testng.annotations.Test;

/**
 * Reproduces deserialization failure with deeply nested HashMap subclasses.
 *
 * <p>This test demonstrates an issue where 4-level HashMap subclass nesting causes deserialization
 * to fail.

 * <p><b>Nesting structure:</b>
 *
 * <pre>
 * ConfigDocument
 *   └─ LocalizationSettings extends HashMap&lt;String, LocaleMapping&gt;
 *       └─ LocaleMapping extends HashMap&lt;String, LanguageData&gt;
 *           └─ LanguageData extends HashMap&lt;String, RegionCode&gt;
 *               └─ RegionCode extends HashMap&lt;String, String&gt;
 * </pre>
 */
public class NestedHashMapSubclassSerializationTest extends ForyTestBase {

  /** Innermost level: Maps region codes to display names. */
  public static class RegionCode extends HashMap<String, String> {}

  /** Third level: Maps language identifiers to region codes. */
  public static class LanguageData extends HashMap<String, RegionCode> {}

  /** Second level: Maps locale identifiers to language data. */
  public static class LocaleMapping extends HashMap<String, LanguageData> {}

  /** Top level: Maps configuration keys to locale mappings. */
  public static class LocalizationSettings extends HashMap<String, LocaleMapping> {}

  /** Document containing 4-level nested HashMap subclass hierarchy. */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  public static class ConfigDocument {
    private String id;
    private LocalizationSettings localizations;
  }

  /**
   * Tests 4-level nested HashMap subclasses with both codegen enabled and disabled.
   *
   * <p>Fails with both configurations, indicating the issue is not specific to codegen.
   */
  @Test(dataProvider = "enableCodegen")
  public void testNestedHashMapSubclassSerialization(boolean enableCodegen) {
    Fory fory =
        Fory.builder()
            .withCodegen(enableCodegen)
            .withRefTracking(false)
            .requireClassRegistration(false)
            .withLanguage(Language.JAVA)
            .build();

    // Build nested structure
    RegionCode usCanada = new RegionCode();
    usCanada.put("US", "United States");
    usCanada.put("CA", "Canada");

    RegionCode europe = new RegionCode();
    europe.put("GB", "United Kingdom");
    europe.put("FR", "France");

    LanguageData englishFrench = new LanguageData();
    englishFrench.put("en", usCanada);
    englishFrench.put("fr", europe);

    LanguageData spanish = new LanguageData();
    spanish.put("es", europe);

    LocaleMapping primary = new LocaleMapping();
    primary.put("language1", englishFrench);
    primary.put("language2", spanish);

    LocaleMapping secondary = new LocaleMapping();
    secondary.put("language3", englishFrench);

    LocalizationSettings localizations = new LocalizationSettings();
    localizations.put("mapping1", primary);
    localizations.put("mapping2", secondary);

    ConfigDocument doc = new ConfigDocument("doc-123", localizations);

    // Test serialization/deserialization
    ConfigDocument deserialized = serDe(fory, doc);
    assertEquals(deserialized, doc);
  }

  @Test
  public void testNestedHashMapSubclassWithCodegenDisabled() {
    Fory fory =
        Fory.builder()
            .withCodegen(false)
            .withAsyncCompilation(false)
            .withRefTracking(false)
            .requireClassRegistration(false)
            .withCompatibleMode(CompatibleMode.COMPATIBLE)
            .withLanguage(Language.JAVA)
            .build();

    // Build 4-level nested structure with codegen disabled
    RegionCode region1 = new RegionCode();
    region1.put("US", "United States");
    region1.put("MX", "Mexico");

    RegionCode region2 = new RegionCode();
    region2.put("DE", "Germany");
    region2.put("IT", "Italy");

    LanguageData lang1 = new LanguageData();
    lang1.put("english", region1);
    lang1.put("german", region2);

    LanguageData lang2 = new LanguageData();
    lang2.put("spanish", region1);

    LocaleMapping locale1 = new LocaleMapping();
    locale1.put("americas", lang1);
    locale1.put("europe", lang2);

    LocaleMapping locale2 = new LocaleMapping();
    locale2.put("asia", lang1);

    LocalizationSettings localizations = new LocalizationSettings();
    localizations.put("primary", locale1);
    localizations.put("secondary", locale2);

    ConfigDocument doc = new ConfigDocument("config-456", localizations);

    // Test serialization/deserialization
    ConfigDocument deserialized = serDe(fory, doc);
    assertEquals(deserialized, doc);
  }

  /** TreeSet subclass for mixed collection test */
  public static class CustomDocuments extends TreeSet<CustomDocument> {
    public CustomDocuments() {
      super();
    }

    public static CustomDocuments empty() {
      return new CustomDocuments();
    }

    public static Collector<CustomDocument, ?, CustomDocuments> collector() {
      return Collectors.collectingAndThen(
          Collectors.toCollection(TreeSet::new),
          set -> {
            CustomDocuments docs = new CustomDocuments();
            docs.addAll(set);
            return docs;
          });
    }

    public static CustomDocuments of(Collection<CustomDocument> multiple) {
      return multiple.stream().collect(collector());
    }
  }

  /** Document class for TreeSet */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  @EqualsAndHashCode
  public static class CustomDocument implements Comparable<CustomDocument> {
    private String id;
    private String name;

    @Override
    public int compareTo(CustomDocument o) {
      return this.id.compareTo(o.id);
    }
  }

  /**
   * Test combining TreeSet subclasses AND HashMap subclasses in the same structure. This simulates
   * a complex real-world scenario.
   */
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  public static class ComplexDocument {
    private String id;
    private LocalizationSettings localizations; // 4-level HashMap subclass nesting
    private CustomDocuments documents; // TreeSet subclass
    private Map<String, CustomDocuments> documentsByCategory; // Map of TreeSet subclasses
  }

  @Test
  public void testMixedCollectionSubclassesWithCodegenDisabled() {
    Fory fory =
        Fory.builder()
            .withCodegen(false)
            .withAsyncCompilation(false)
            .withRefTracking(false)
            .requireClassRegistration(false)
            .withCompatibleMode(CompatibleMode.COMPATIBLE)
            .withLanguage(Language.JAVA)
            .build();

    // Build 4-level HashMap nesting
    RegionCode region = new RegionCode();
    region.put("US", "United States");
    region.put("CA", "Canada");

    LanguageData lang = new LanguageData();
    lang.put("en", region);

    LocaleMapping locale = new LocaleMapping();
    locale.put("americas", lang);

    LocalizationSettings localizations = new LocalizationSettings();
    localizations.put("primary", locale);

    // Build TreeSet subclass
    CustomDocuments docs1 = CustomDocuments.empty();
    docs1.add(new CustomDocument("1", "Doc One"));
    docs1.add(new CustomDocument("2", "Doc Two"));

    CustomDocuments docs2 = CustomDocuments.empty();
    docs2.add(new CustomDocument("3", "Doc Three"));

    // Build Map of TreeSet subclasses
    Map<String, CustomDocuments> docsByCategory = new HashMap<>();
    docsByCategory.put("category1", docs1);
    docsByCategory.put("category2", docs2);

    ComplexDocument complexDoc =
        new ComplexDocument("complex-789", localizations, docs1, docsByCategory);

    // Test serialization/deserialization
    ComplexDocument deserialized = serDe(fory, complexDoc);
    assertEquals(deserialized, complexDoc);
  }
}
```

### What did you expect to see?

Deserialization of nested HashMap subclasses should succeed, producing objects equal to the originals.

### What did you see instead?

**In `SCHEMA_CONSISTENT` mode**, deserialization fails with `NullPointerException` in `MapLikeSerializer.readJavaChunkGeneric`:

```
org.apache.fory.exception.DeserializationException: deserialize obj of class ChildContainerSerializersTest$ChildHashMap4 failed
  at org.apache.fory.Fory.deserialize(Fory.java:523)
Caused by: java.lang.NullPointerException
  at org.apache.fory.serializer.collection.MapLikeSerializer.readJavaChunkGeneric(MapLikeSerializer.java:336)
  at org.apache.fory.serializer.collection.MapLikeSerializer.readJavaChunk(MapLikeSerializer.java:315)
  at org.apache.fory.serializer.collection.MapLikeSerializer.generalJavaRead(MapLikeSerializer.java:304)
  at org.apache.fory.serializer.collection.MapSerializer.read(MapSerializer.java:123)
```

**In `COMPATIBLE` mode**, deserialization fails with `IndexOutOfBoundsException` in `MetaContext.readTypeInfos`:

```
org.apache.fory.exception.DeserializationException: deserialize obj of class ChildContainerSerializersTest$ChildMapHolder failed
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
  at java.base/java.util.Objects.checkIndex(Objects.java:372)
  at java.base/java.util.ArrayList.get(ArrayList.java:459)
  at org.apache.fory.resolver.MetaContext.getTypeInfo(MetaContext.java:69)
  at org.apache.fory.resolver.ClassResolver.readClassInfo(ClassResolver.java:1091)
```

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by mandrean**
## Why?                                                                                                                                                                                                                                                                                                                     
Deserializing nested HashMap subclasses (e.g. `class MyMap extends HashMap<String, MyOtherMap>`) throws NPE in both `SCHEMA_CONSISTENT` and `COMPATIBLE` modes. Two distinct bugs cause this.

## What does this PR do?

**Bug 1: Write/read generics push asymmetry in `MapLikeSerializer.readJavaChunkGeneric`**

The write path in `writeJavaChunkGeneric` always pushes generic types onto the `Generics` stack, but the read path conditionally pushed them based on `hasGenericParameters()`. For nested HashMap subclasses without own type parameters (only inherited ones), `hasGenericParameters()` returns false, causing inner maps
  to fall into the non-generic read path while bytes were written by the generic path. This results in a null serializer when `KEY_DECL_TYPE`/`VALUE_DECL_TYPE` chunk flags are set.

**Fix 1:** Remove the conditional branch and always push/pop generics symmetrically, matching the write path.

**Bug 2: Meta context index desync in `ChildContainerSerializers.readAndSkipLayerClassMeta`**

In COMPATIBLE mode, `writeLayerClassMeta` adds layer marker classes to `metaContext.classMap`, which shares the same index space as `writeSharedClassMeta`. However, `readAndSkipLayerClassMeta` skipped the bytes without adding entries to `metaContext.readTypeInfos`. This caused subsequent `readSharedClassMeta`
  reference lookups to use wrong indices.

**Fix 2:** Add a `null` placeholder to `metaContext.readTypeInfos` after skipping a new layer meta entry.

## Related issues

Fixes #3337

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change? No
- [ ] Does this PR introduce any binary protocol compatibility change? No

Binary compatibility is safe. The fix only changes the read path, it doesn't change what bytes are written. The write path was already always pushing generics and writing with KEY_DECL_TYPE/VALUE_DECL_TYPE flags set. The read path now correctly consumes those same bytes.

For bug 2, the fix only adds a bookkeeping placeholder on the read side, writing is untouched.

Old writers + new readers: works. New writers + old readers: unchanged (write path is identical)

 ## Benchmark

Bug 1 fix removes a conditional branch (one fewer branch per chunk iteration), so performance should be equal or marginally better.

Bug 2 fix adds a single `ArrayList.add(null)` call per new layer meta entry, which is negligible.

### CODE REVIEW

File: java/fory-core/src/main/java/org/apache/fory/serializer/collection/MapLikeSerializer.java [hunk 1]
```diff
@@ -853,43 +853,25 @@ private long readJavaChunkGeneric(
...
-                ? binding.readRef(buffer, keySerializer)
-                : binding.read(buffer, keySerializer);
-        Object value =
-            trackValueRef
-                ? binding.readRef(buffer, valueSerializer)
-                : binding.read(buffer, valueSerializer);
-        fory.decDepth();
-        map.put(key, value);
-        size--;
-      }
```
Comment (mandrean) [inline java/fory-core/src/main/java/org/apache/fory/serializer/collection/MapLikeSerializer.java:892]: I think the else branch was a premature read-side optimization that had no corresponding branch on the write side (`writeJavaChunkGeneric` always pushes generics unconditionally). This asymmetry caused the read path to skip generic type propagation for `HashMap` subclasses whose type parameters are inherited rather than declared directly (e.g. class `MyMap extends HashMap<String, String>`), leading to NPE when the reader encountered chunk flags (`KEY_DECL_TYPE`/`VALUE_DECL_TYPE`) that were written assuming generics were on the stack.

Comment (chaokunyang) [reply java/fory-core/src/main/java/org/apache/fory/serializer/collection/MapLikeSerializer.java:892]: Good catch.
