### PR TITLE
fix(ci): add retry logic to Bazel downloads to prevent flaky CI failures

### LINKED ISSUE #2731: [CI] Python CI is unstable because of downloading bazel error
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/fory/issues) and found no similar issues.

### Version

Latest

### Component(s)

Other

### Description
Python CI randomly fails sometimes.

### Minimal reproduce step

submit a pr

### What did you expect to see?

ci pass

### What did you see instead?
log: [Python CI (3.13.3, ubuntu-24.04-arm)](https://github.com/apache/fory/actions/runs/18349720040/job/52266048481?pr=2724#logs)
```
Running command Getting requirements to build editable
  2025/10/08 15:25:24 Downloading https://releases.bazel.build/6.3.2/release/bazel-6.3.2-linux-arm64...
  2025/10/08 15:25:29 could not download Bazel: failed to download bazel: failed to download bazel: could not copy from https://releases.bazel.build/6.3.2/release/bazel-6.3.2-linux-arm64 to /home/runner/.cache/bazelisk/downloads/_tmp/download1245162363: stream error: stream ID 1; INTERNAL_ERROR; received from peer
  DEBUG = False, BAZEL_BUILD_EXT = True, PATH = /tmp/pip-build-env-8vv6bk_o/overlay/bin:/tmp/pip-build-env-8vv6bk_o/normal/bin:/opt/hostedtoolcache/Python/3.13.3/arm64/bin:/opt/hostedtoolcache/Python/3.13.3/arm64:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/opt/google-cloud-sdk/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  setup_dir: /home/runner/work/fory/fory/python
  project_dir: /home/runner/work/fory/fory
  fory_cpp_src_dir: /home/runner/work/fory/fory/src
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.13.3/arm64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "/opt/hostedtoolcache/Python/3.13.3/arm64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.13.3/arm64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 157, in get_requires_for_build_editable
      return hook(config_settings)
    File "/tmp/pip-build-env-8vv6bk_o/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 473, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-8vv6bk_o/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/pip-build-env-8vv6bk_o/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "/tmp/pip-build-env-8vv6bk_o/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 64, in <module>
    File "/tmp/pip-build-env-8vv6bk_o/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 115, in setup
      return distutils.core.setup(**attrs)
             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    File "/tmp/pip-build-env-8vv6bk_o/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 148, in setup
      _setup_distribution = dist = klass(attrs)
                                   ~~~~~^^^^^^^
    File "<string>", line 57, in __init__
    File "/opt/hostedtoolcache/Python/3.13.3/arm64/lib/python3.13/subprocess.py", line 419, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['bazel', 'build', '-s', '--copt=-fsigned-char', '//:cp_fory_so']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/hostedtoolcache/Python/3.13.3/arm64/bin/python /opt/hostedtoolcache/Python/3.13.3/arm64/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_editable /tmp/tmpzt54lry5
  cwd: /home/runner/work/fory/fory/python
  Getting requirements to build editable: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

### Anything Else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by SanyamSuyal**
### Problem
Fixes #2731

Python CI is unstable because of downloading Bazel error. The CI randomly fails with:
could not download Bazel: failed to download bazel: stream error: stream ID 1; INTERNAL_ERROR; received from peer

### Solution
Added retry logic with exponential backoff (5 attempts with 2s, 4s, 8s, 16s, 32s delays) to handle transient network errors from GitHub CDN.

### Changes
- ci/run_ci.sh: Added retry loop in install_bazel() function
- ci/tasks/common.py: Added urlretrieve_with_retries() helper function

### Impact
- No breaking changes
- Fully backward compatible
- Reduces CI flakiness significantly

Fixes #2731

### CODE REVIEW

File: ci/run_ci.sh [hunk 1]
```diff
@@ -96,7 +96,23 @@ install_bazel() {
   BINARY_URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-${OS}-${ARCH}"
 
   echo "Downloading bazel from: $BINARY_URL"
-  curl -L -sSf -o "$BAZEL_DIR/bazel" "$BINARY_URL" || { echo "Failed to download bazel"; exit 1; }
+  # Retry download with exponential backoff to avoid transient network errors in CI
+  MAX_ATTEMPTS=5
+  SLEEP_SECONDS=2
+  attempt=1
+  while [ $attempt -le $MAX_ATTEMPTS ]; do
+    if curl -L -sSf -o "$BAZEL_DIR/bazel" "$BINARY_URL"; then
```
Comment (chaokunyang) [inline ci/run_ci.sh:104]: do we need to delete previous file? or it will overwrite directly?

File: ci/tasks/common.py [hunk 2]
```diff
@@ -88,6 +87,34 @@ def get_bazel_download_url():
...
+
+    Raises the last exception if all attempts fail.
+    """
+    attempt = 1
+    delay = initial_delay
+    last_exc = None
+    while attempt <= max_attempts:
+        try:
+            logging.info(f"Downloading (attempt {attempt}) {url} -> {filename}")
+            ulib.urlretrieve(url, filename)
```
Comment (chaokunyang) [inline ci/tasks/common.py:101]: ditto

File: ci/run_ci.sh (hunk 1 above)
Comment (SanyamSuyal) [reply ci/run_ci.sh:104]: > do we need to delete previous file? or it will overwrite directly?

Hey , By default `curl -o` will overwrite the target file, but that can leave a partially downloaded/ corrupted file if the download is interrupted.

To be safer I can change the script to download to a temporary file (e.g. `bazel.tmp`) and `mv` it into place only after the download succeeds. That avoids replacing a working binary with a partial file. I can apply the same approach in the Python installer helper too. Would you like me to update the PR with that change?

File: ci/tasks/common.py (hunk 2 above)
Comment (SanyamSuyal) [reply ci/tasks/common.py:101]: > ditto

Yes, it overwrites directly. The curl -o flag and urlretrieve will replace the target file.

**Comment by urlyy** [comment]
It seems like Bazel binary could be **cached in GitHub Actions** to avoid downloading it on every run. Is it possible to set up a cache for Bazel in our workflows?

If it could, here are the benefits:
1. Faster builds: reuse Bazel binary instead of downloading every run.
2. More reliable: reduce network failures during downloads.
3. Cost saving: less CI runtime and resource usage.

**Comment by SanyamSuyal** [comment]
> It seems like Bazel binary could be **cached in GitHub Actions** to avoid downloading it on every run. Is it possible to set up a cache for Bazel in our workflows?
> 
> If it could, here are the benefits:
> 
> 1. Faster builds: reuse Bazel binary instead of downloading every run.
> 2. More reliable: reduce network failures during downloads.
> 3. Cost saving: less CI runtime and resource usage.

Good idea! @urlyy  I can add caching as a follow-up improvement.
We have two options:

1. GitHub Actions cache - Simple, caches the binary directly
2. Bazelisk - Tool that auto-manages Bazel versions with caching

Which do you prefer?

File: ci/run_ci.sh (hunk 1 above)
Comment (chaokunyang) [reply ci/run_ci.sh:104]: It's OK with current commit, no need to add another fix.

**Comment by chaokunyang** [comment]
> > It seems like Bazel binary could be **cached in GitHub Actions** to avoid downloading it on every run. Is it possible to set up a cache for Bazel in our workflows?
> > If it could, here are the benefits:
> > 
> > 1. Faster builds: reuse Bazel binary instead of downloading every run.
> > 2. More reliable: reduce network failures during downloads.
> > 3. Cost saving: less CI runtime and resource usage.
> 
> Good idea! @urlyy I can add caching as a follow-up improvement. We have two options:
> 
> 1. GitHub Actions cache - Simple, caches the binary directly
> 2. Bazelisk - Tool that auto-manages Bazel versions with caching
> 
> Which do you prefer?

could you open a new issue for this? I think this PR can be merged now

**Comment by urlyy** [comment]
> > > It seems like Bazel binary could be **cached in GitHub Actions** to avoid downloading it on every run. Is it possible to set up a cache for Bazel in our workflows?
> 
> > > If it could, here are the benefits:
> 
> > > 
> 
> > > 1. Faster builds: reuse Bazel binary instead of downloading every run.
> 
> > > 2. More reliable: reduce network failures during downloads.
> 
> > > 3. Cost saving: less CI runtime and resource usage.
> 
> > 
> 
> > Good idea! @urlyy I can add caching as a follow-up improvement. We have two options:
> 
> > 
> 
> > 1. GitHub Actions cache - Simple, caches the binary directly
> 
> > 2. Bazelisk - Tool that auto-manages Bazel versions with caching
> 
> > 
> 
> > Which do you prefer?
> 
> 
> 
> could you open a new issue for this? I think this PR can be merged now

I think Fory doesn’t seem to need managing multiple Bazel versions — caching the binary directly is enough. @chaokunyang
